export const SETTING_KEYS = {
  CHAT_MAX_TURNS: 'CHAT_MAX_TURNS',
  CHAT_SYSTEM_PROMPT: 'CHAT_SYSTEM_PROMPT',
  MCQ_WEIGHT: 'MCQ_WEIGHT',
  INTERVIEW_WEIGHT: 'INTERVIEW_WEIGHT',
  ASSESSMENT_QUESTION_COUNT: 'ASSESSMENT_QUESTION_COUNT',
  ASSESSMENT_DURATION_MINUTES: 'ASSESSMENT_DURATION_MINUTES',
} as const;

export type SettingKey = typeof SETTING_KEYS[keyof typeof SETTING_KEYS];
