import { MENU_ADMIN } from '@/modules/shared/constants';
import { IMenu } from '@/types/navigations';

const Menuitems: IMenu[] = [
  {
    data: {
      id: 0,
      code: 'OVERVIEW',
      icon: 'pie-chart-2-linear',
      link: '/admin/overview',
      name: 'menu.overview',
      type: 'basic',
      title: 'menu.overview',
      priAccess: MENU_ADMIN,
      priRead: MENU_ADMIN,
      priInsert: MENU_ADMIN,
      priUpdate: MENU_ADMIN,
      priDelete: MENU_ADMIN,
      priImport: MENU_ADMIN,
      priExport: MENU_ADMIN,
      children: [],
      target: null,
      subtitle: null,
      execType: 'TC',
      parentId: 0,
      externalLink: null,
      navigationIconId: 0,
      navigationTypeId: 0,
      path: '',
      lvl: 0,
    },
    children: [],
    parentId: 0,
  },
  {
    data: {
      id: 3,
      code: 'QUESTION',
      icon: 'document-text-linear',
      link: '/admin/questions',
      name: 'menu.question',
      type: 'basic',
      title: 'menu.question',
      priAccess: MENU_ADMIN,
      priRead: MENU_ADMIN,
      priInsert: MENU_ADMIN,
      priUpdate: MENU_ADMIN,
      priDelete: MENU_ADMIN,
      priImport: MENU_ADMIN,
      priExport: MENU_ADMIN,
      children: [],
      target: null,
      subtitle: null,
      execType: 'TC',
      parentId: 0,
      externalLink: null,
      navigationIconId: 0,
      navigationTypeId: 0,
      path: '',
      lvl: 0,
    },
    children: [],
    parentId: 0,
  },
  {
    data: {
      id: 2,
      code: 'SUBMISSION',
      icon: 'clipboard-check-linear',
      link: '/admin/submissions',
      name: 'menu.submission',
      type: 'basic',
      title: 'menu.submission',
      priAccess: MENU_ADMIN,
      priRead: MENU_ADMIN,
      priInsert: MENU_ADMIN,
      priUpdate: MENU_ADMIN,
      priDelete: MENU_ADMIN,
      priImport: MENU_ADMIN,
      priExport: MENU_ADMIN,
      children: [],
      target: null,
      subtitle: null,
      execType: 'TC',
      parentId: 0,
      externalLink: null,
      navigationIconId: 0,
      navigationTypeId: 0,
      path: '',
      lvl: 0,
    },
    children: [],
    parentId: 0,
  },
  {
    data: {
      id: 1,
      code: 'RESOURCE',
      icon: 'box-linear',
      link: '/admin/resources',
      name: 'menu.resource',
      type: 'basic',
      title: 'menu.resource',
      priAccess: MENU_ADMIN,
      priRead: MENU_ADMIN,
      priInsert: MENU_ADMIN,
      priUpdate: MENU_ADMIN,
      priDelete: MENU_ADMIN,
      priImport: MENU_ADMIN,
      priExport: MENU_ADMIN,
      children: [],
      target: null,
      subtitle: null,
      execType: 'TC',
      parentId: 0,
      externalLink: null,
      navigationIconId: 0,
      navigationTypeId: 0,
      path: '',
      lvl: 0,
    },
    children: [],
    parentId: 0,
  },
  {
    data: {
      id: 4,
      code: 'USER',
      icon: 'user-linear',
      link: '/admin/users',
      name: 'menu.user',
      type: 'basic',
      title: 'menu.user',
      priAccess: MENU_ADMIN,
      priRead: MENU_ADMIN,
      priInsert: MENU_ADMIN,
      priUpdate: MENU_ADMIN,
      priDelete: MENU_ADMIN,
      priImport: MENU_ADMIN,
      priExport: MENU_ADMIN,
      children: [],
      target: null,
      subtitle: null,
      execType: 'TC',
      parentId: 0,
      externalLink: null,
      navigationIconId: 0,
      navigationTypeId: 0,
      path: '',
      lvl: 0,
    },
    children: [],
    parentId: 0,
  },
];

export default Menuitems;
